//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int LineNumber { get; set; }
        public string ProductName { get; set; }
        public int CarId { get; set; }
        public int TariffId { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public decimal PricePerUnit { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Tariffs Tariffs { get; set; }
    }
}
