//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSpecifications
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int MaterialId { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Services Services1 { get; set; }
    }
}
