//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkReports()
        {
            this.WorkReportMaterials = new HashSet<WorkReportMaterials>();
        }
    
        public int Id { get; set; }
        public string ReportNumber { get; set; }
        public System.DateTime ReportDate { get; set; }
        public int CarId { get; set; }
        public int ServiceId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Unit { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Services Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkReportMaterials> WorkReportMaterials { get; set; }
    }
}
